data:
  batch_size: 16
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 
  - 12
  - 5000
  data_path: ecgs_train_BMI_balanced_noBase_gn.pt
  validation: false
  val_path: None
  num_workers: 1
  pin_mem: true
  root_path: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/projects/ecg/
  rescale_sigma: 0
  ftsurrogate: 0.1
  jitter: 
  - 0
  - 0
  spec_augment: 
  - 0.25
  - 120
  time_flip: 0
  sign_flip: 0
logging:
  folder: ./logs/vitb14.224-bs.2048-ep.3/
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.2 #0.75
  - 0.3 #1.5
  enc_mask_scale:
  - 1.0
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 
  - 1
  - 100
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 4
  pred_emb_dim: 192
  read_checkpoint: null
  use_bfloat16: false
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 3
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 1e-4 #0.001
  start_lr: 1e-5 #0.0002
  warmup: 3
  weight_decay: 0.04
