data:
  batch_size: 64
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 
  - 12
  - 5000
  data_path: mimic_data_0-10000
  val_path: mimic_data_10000-10100
  num_workers: 10
  pin_mem: true
  root_path: $./
  rescale_sigma: 0
  permutation: False
  jitter: 
  - 0
  - 0
  shift: 
  - 0
  - 0
  time_flip: 0
  sign_flip: 0
logging:
  folder: ./logs/vith14.224-bs.2048-ep.300/
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.2 #0.75
  - 0.3 #1.5
  enc_mask_scale:
  - 1.0
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 8
  patch_size: 
  - 1
  - 100
  pred_mask_scale:
  - 0.2
  - 0.4
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_min
  pred_depth: 1
  pred_emb_dim: 12
  read_checkpoint: null
  use_bfloat16: false
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 5
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04
