data:
  batch_size: 16
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 
  - 12
  - 5000
  data_path: ecgs_train_ecg_imaging_noBase_gn.pt
  val_path: None
  downstream_train_path: ecgs_train_flutter_all_balanced_noBase_gn.pt
  downstream_val_path: ecgs_val_flutter_all_balanced_noBase_gn.pt
  num_workers: 0
  pin_mem: true
  root_path: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/projects/ecg/
  rescale_sigma: 0.5
  ftsurrogate: 0.1
  jitter: 
  - 0.25
  - 0.6
  spec_augment: 
  - 0.25
  - 120
  time_flip: 0.5
  sign_flip: 0.5
logging:
  #folder: ./logs/vitt-ep.100/
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.2 #0.75
  - 0.3 #1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 
  - 1
  - 100
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_tiny
  pred_depth: 4
  pred_emb_dim: 48
  read_checkpoint: null
  use_bfloat16: false
optimization:
  ema:
  - 0.996
  - 0.996
  epochs: 100
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 13
  weight_decay: 0.04
